<?php

namespace UnaGauchada\CreditBundle\Repository;

/**
 * TransactionReasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionReasonRepository extends \Doctrine\ORM\EntityRepository
{
}
