use unaGauchadaDB;

INSERT INTO province (id,name) VALUES(1,'BUENOS AIRES');
INSERT INTO province (id,name) VALUES(2,'CATAMARCA');
INSERT INTO province (id,name) VALUES(3,'CHACO');
INSERT INTO province (id,name) VALUES(4,'CHUBUT');
INSERT INTO province (id,name) VALUES(5,'CORDOBA');
INSERT INTO province (id,name) VALUES(6,'CORRIENTES');
INSERT INTO province (id,name) VALUES(7,'ENTRE RIOS');
INSERT INTO province (id,name) VALUES(8,'FORMOSA');
INSERT INTO province (id,name) VALUES(9,'JUJUY');
INSERT INTO province (id,name) VALUES(10,'LA PAMPA');
INSERT INTO province (id,name) VALUES(11,'LA RIOJA');
INSERT INTO province (id,name) VALUES(12,'MENDOZA');
INSERT INTO province (id,name) VALUES(13,'MISIONES');
INSERT INTO province (id,name) VALUES(14,'NEUQUEN');
INSERT INTO province (id,name) VALUES(15,'RIO NEGRO');
INSERT INTO province (id,name) VALUES(16,'SALTA');
INSERT INTO province (id,name) VALUES(17,'SAN JUAN');
INSERT INTO province (id,name) VALUES(18,'SAN LUIS');
INSERT INTO province (id,name) VALUES(19,'SANTA CRUZ');
INSERT INTO province (id,name) VALUES(20,'SANTA FE');
INSERT INTO province (id,name) VALUES(21,'SANTIAGO DEL ESTERO');
INSERT INTO province (id,name) VALUES(22,'TIERRA DEL FUEGO');
INSERT INTO province (id,name) VALUES(23,'TUCUMAN');
INSERT INTO province (id,name) VALUES(24,'');


INSERT INTO department (id,province_id,name) VALUES(1,1,'AZUL');
INSERT INTO department (id,province_id,name) VALUES(2,1,'PUAN');
INSERT INTO department (id,province_id,name) VALUES(3,1,'LA MATANZA');
INSERT INTO department (id,province_id,name) VALUES(4,1,'TIGRE');
INSERT INTO department (id,province_id,name) VALUES(5,1,'25 DE MAYO');
INSERT INTO department (id,province_id,name) VALUES(6,1,'TRENQUE LAUQUEN');
INSERT INTO department (id,province_id,name) VALUES(7,1,'9 DE JULIO');
INSERT INTO department (id,province_id,name) VALUES(8,1,'LANUS');
INSERT INTO department (id,province_id,name) VALUES(9,1,'LA PLATA');
INSERT INTO department (id,province_id,name) VALUES(10,1,'MONTE');
INSERT INTO department (id,province_id,name) VALUES(11,1,'PEHUAJO');
INSERT INTO department (id,province_id,name) VALUES(12,1,'SAN ISIDRO');
INSERT INTO department (id,province_id,name) VALUES(13,1,'PERGAMINO');
INSERT INTO department (id,province_id,name) VALUES(14,1,'ALBERTI');
INSERT INTO department (id,province_id,name) VALUES(15,1,'CHASCOMUS');
INSERT INTO department (id,province_id,name) VALUES(16,1,'ESTEBAN ECHEVERRIA');
INSERT INTO department (id,province_id,name) VALUES(17,1,'MERCEDES');
INSERT INTO department (id,province_id,name) VALUES(18,1,'BAHIA BLANCA');
INSERT INTO department (id,province_id,name) VALUES(19,1,'MERLO');
INSERT INTO department (id,province_id,name) VALUES(20,1,'JUNIN');
INSERT INTO department (id,province_id,name) VALUES(21,1,'GUAMINI');
INSERT INTO department (id,province_id,name) VALUES(22,1,'LUJAN');
INSERT INTO department (id,province_id,name) VALUES(23,1,'LEANDRO N.ALEM');
INSERT INTO department (id,province_id,name) VALUES(24,1,'MATANZA');
INSERT INTO department (id,province_id,name) VALUES(25,1,'GENERAL PAZ');
INSERT INTO department (id,province_id,name) VALUES(26,1,'SAN VICENTE');
INSERT INTO department (id,province_id,name) VALUES(27,1,'CAÑUELAS');
INSERT INTO department (id,province_id,name) VALUES(28,1,'ALMIRANTE BROWN');
INSERT INTO department (id,province_id,name) VALUES(29,1,'CNL.DE MARINA  L.ROSALES');
INSERT INTO department (id,province_id,name) VALUES(30,1,'BARADERO');
INSERT INTO department (id,province_id,name) VALUES(31,1,'SAAVEDRA');
INSERT INTO department (id,province_id,name) VALUES(32,1,'BRANDSEN');
INSERT INTO department (id,province_id,name) VALUES(33,1,'GENERAL SARMIENTO');
INSERT INTO department (id,province_id,name) VALUES(34,1,'TAPALQUE');
INSERT INTO department (id,province_id,name) VALUES(35,1,'SALADILLO');
INSERT INTO department (id,province_id,name) VALUES(36,1,'MAGDALENA');
INSERT INTO department (id,province_id,name) VALUES(37,1,'GONZALES CHAVES');
INSERT INTO department (id,province_id,name) VALUES(38,1,'GENERAL PINTO');
INSERT INTO department (id,province_id,name) VALUES(39,1,'NAVARRO');
INSERT INTO department (id,province_id,name) VALUES(40,1,'DAIREAUX');
INSERT INTO department (id,province_id,name) VALUES(41,1,'LOBOS');
INSERT INTO department (id,province_id,name) VALUES(42,1,'CORONEL DORREGO');
INSERT INTO department (id,province_id,name) VALUES(43,1,'ADOLFO ALSINA');
INSERT INTO department (id,province_id,name) VALUES(44,1,'COLON');
INSERT INTO department (id,province_id,name) VALUES(45,1,'GENERAL ARENALES');
INSERT INTO department (id,province_id,name) VALUES(46,1,'LINCOLN');
INSERT INTO department (id,province_id,name) VALUES(47,1,'VILLARINO');
INSERT INTO department (id,province_id,name) VALUES(48,1,'VICENTE LOPEZ');
INSERT INTO department (id,province_id,name) VALUES(49,1,'BARTOLOME MITRE');
INSERT INTO department (id,province_id,name) VALUES(50,1,'EXALTACION DE LA CRUZ');
INSERT INTO department (id,province_id,name) VALUES(51,1,'SALTO');
INSERT INTO department (id,province_id,name) VALUES(52,1,'BRAGADO');
INSERT INTO department (id,province_id,name) VALUES(53,1,'ZARATE');
INSERT INTO department (id,province_id,name) VALUES(54,1,'AVELLANEDA');
INSERT INTO department (id,province_id,name) VALUES(55,1,'AYACUCHO');
INSERT INTO department (id,province_id,name) VALUES(56,1,'SAN ANDRES DE GILES');
INSERT INTO department (id,province_id,name) VALUES(57,1,'TANDIL');
INSERT INTO department (id,province_id,name) VALUES(58,1,'RIVADAVIA');
INSERT INTO department (id,province_id,name) VALUES(59,1,'PATAGONES');
INSERT INTO department (id,province_id,name) VALUES(60,1,'GRL.VIAMONTE');
INSERT INTO department (id,province_id,name) VALUES(61,1,'CNL.DE MARINA LEONARDO ROSALES');
INSERT INTO department (id,province_id,name) VALUES(62,1,'BALCARCE');
INSERT INTO department (id,province_id,name) VALUES(63,1,'TRES ARROYOS');
INSERT INTO department (id,province_id,name) VALUES(64,1,'GENERAL VILLEGAS');
INSERT INTO department (id,province_id,name) VALUES(65,1,'LOMAS DE ZAMORA');
INSERT INTO department (id,province_id,name) VALUES(66,1,'BERISSO');
INSERT INTO department (id,province_id,name) VALUES(67,1,'JUAREZ');
INSERT INTO department (id,province_id,name) VALUES(68,1,'GRL.PUEYRREDON');
INSERT INTO department (id,province_id,name) VALUES(69,1,'CORONEL SUAREZ');
INSERT INTO department (id,province_id,name) VALUES(70,1,'ESCOBAR');
INSERT INTO department (id,province_id,name) VALUES(71,1,'CARLOS CASARES');
INSERT INTO department (id,province_id,name) VALUES(72,1,'CHIVILCOY');
INSERT INTO department (id,province_id,name) VALUES(73,1,'BERAZATEGUI');
INSERT INTO department (id,province_id,name) VALUES(74,1,'QUILMES');
INSERT INTO department (id,province_id,name) VALUES(75,1,'TORQUINST');
INSERT INTO department (id,province_id,name) VALUES(76,1,'3 DE FEBRERO');
INSERT INTO department (id,province_id,name) VALUES(77,1,'OLAVARRIA');
INSERT INTO department (id,province_id,name) VALUES(78,1,'PELLEGRINI');
INSERT INTO department (id,province_id,name) VALUES(79,1,'GENERAL BELGANO');
INSERT INTO department (id,province_id,name) VALUES(80,1,'FLORENCIO VARELA');
INSERT INTO department (id,province_id,name) VALUES(81,1,'SALLIQUELO');
INSERT INTO department (id,province_id,name) VALUES(82,1,'CNL.DE MARINA L.ROSALES');
INSERT INTO department (id,province_id,name) VALUES(83,1,'MAR CHIQUITA');
INSERT INTO department (id,province_id,name) VALUES(84,1,'GENERAL PUEYRREDON');
INSERT INTO department (id,province_id,name) VALUES(85,1,'CAMPANA');
INSERT INTO department (id,province_id,name) VALUES(86,1,'GRL.SARMIENTO');
INSERT INTO department (id,province_id,name) VALUES(87,1,'ROJAS');
INSERT INTO department (id,province_id,name) VALUES(88,1,'SARMIENTO');
INSERT INTO department (id,province_id,name) VALUES(89,1,'CARMEN DE ARECO');
INSERT INTO department (id,province_id,name) VALUES(90,1,'PILA');
INSERT INTO department (id,province_id,name) VALUES(91,1,'TRES DE FEBRERO');
INSERT INTO department (id,province_id,name) VALUES(92,1,'MORON');
INSERT INTO department (id,province_id,name) VALUES(93,1,'CASTELLI');
INSERT INTO department (id,province_id,name) VALUES(94,1,'CHACABUCO');
INSERT INTO department (id,province_id,name) VALUES(95,1,'GENERAL VIAMONTE');
INSERT INTO department (id,province_id,name) VALUES(96,1,'RAUCH');
INSERT INTO department (id,province_id,name) VALUES(97,1,'GENERAL BELGRANO');
INSERT INTO department (id,province_id,name) VALUES(98,1,'TORNQUIST');
INSERT INTO department (id,province_id,name) VALUES(99,1,'NECOCHEA');
INSERT INTO department (id,province_id,name) VALUES(100,1,'MARCOS PAZ');
INSERT INTO department (id,province_id,name) VALUES(101,1,'CARLOS TEJEDOR');
INSERT INTO department (id,province_id,name) VALUES(102,1,'SAN PEDRO');
INSERT INTO department (id,province_id,name) VALUES(103,1,'GENERAL ALVARADO');
INSERT INTO department (id,province_id,name) VALUES(104,1,'SAN NICOLAS');
INSERT INTO department (id,province_id,name) VALUES(105,1,'HIPOLITO YRIGOYEN');
INSERT INTO department (id,province_id,name) VALUES(106,1,'LAS FLORES');
INSERT INTO department (id,province_id,name) VALUES(107,1,'CORONEL PRINGLES');
INSERT INTO department (id,province_id,name) VALUES(108,1,'GENERAL SAN MARTIN');
INSERT INTO department (id,province_id,name) VALUES(109,1,'BENITO JUAREZ');
INSERT INTO department (id,province_id,name) VALUES(110,1,'SAN CAYETANO');
INSERT INTO department (id,province_id,name) VALUES(111,1,'ADOLFO GONZALES CHAVES');
INSERT INTO department (id,province_id,name) VALUES(112,1,'DOLORES');
INSERT INTO department (id,province_id,name) VALUES(113,1,'SAN ANTONIO');
INSERT INTO department (id,province_id,name) VALUES(114,1,'LOBERIA');
INSERT INTO department (id,province_id,name) VALUES(115,1,'RAMALLO');
INSERT INTO department (id,province_id,name) VALUES(116,1,'GENERAL ALVEAR');
INSERT INTO department (id,province_id,name) VALUES(117,1,'ENSENADA');
INSERT INTO department (id,province_id,name) VALUES(118,1,'TORDILLO');
INSERT INTO department (id,province_id,name) VALUES(119,1,'GENERAL GUIDO');
INSERT INTO department (id,province_id,name) VALUES(120,1,'GENERAL LAS HERAS');
INSERT INTO department (id,province_id,name) VALUES(121,1,'GENERAL JUAN MADARIAGA');
INSERT INTO department (id,province_id,name) VALUES(122,1,'GENERAL LA MADRID');
INSERT INTO department (id,province_id,name) VALUES(123,1,'GENERAL LAVALLE');
INSERT INTO department (id,province_id,name) VALUES(124,1,'GENERAL RODRIGUEZ');
INSERT INTO department (id,province_id,name) VALUES(125,1,'GENERAL VLLEGAS');
INSERT INTO department (id,province_id,name) VALUES(126,1,'ADOLFO GONZALEZ CHAVES');
INSERT INTO department (id,province_id,name) VALUES(127,1,'CORONEL DE MARINA L.ROSALES');
INSERT INTO department (id,province_id,name) VALUES(128,1,'BOLIVAR');
INSERT INTO department (id,province_id,name) VALUES(129,1,'SAN FERNANDO');
INSERT INTO department (id,province_id,name) VALUES(130,1,'CAPITAN SARMIENTO');
INSERT INTO department (id,province_id,name) VALUES(131,1,'ROQUE PEREZ');
INSERT INTO department (id,province_id,name) VALUES(132,1,'MORENO');
INSERT INTO department (id,province_id,name) VALUES(133,1,'LAPRIDA');
INSERT INTO department (id,province_id,name) VALUES(134,1,'MAIPU');
INSERT INTO department (id,province_id,name) VALUES(135,1,'ECHEVERRIA');
INSERT INTO department (id,province_id,name) VALUES(136,1,'PILAR');
INSERT INTO department (id,province_id,name) VALUES(137,1,'CORONEL DE MARINA L. ROSALES');
INSERT INTO department (id,province_id,name) VALUES(138,1,'SUIPACHA');
INSERT INTO department (id,province_id,name) VALUES(139,1,'SAN ANTONIO DE ARECO');
INSERT INTO department (id,province_id,name) VALUES(140,1,'BARAZATEGUI');
INSERT INTO department (id,province_id,name) VALUES(141,1,'ALSINA');
INSERT INTO department (id,province_id,name) VALUES(142,1,'LEANDRO N. ELEM');
INSERT INTO department (id,province_id,name) VALUES(143,1,'GRL.SAN MARTIN');
INSERT INTO department (id,province_id,name) VALUES(144,1,'CORONEL');
INSERT INTO department (id,province_id,name) VALUES(145,2,'CAPAYAN');
INSERT INTO department (id,province_id,name) VALUES(146,2,'ANDALGALA');
INSERT INTO department (id,province_id,name) VALUES(147,2,'EL ALTO');
INSERT INTO department (id,province_id,name) VALUES(148,2,'SANTA ROSA');
INSERT INTO department (id,province_id,name) VALUES(149,2,'ANCASTI');
INSERT INTO department (id,province_id,name) VALUES(150,2,'PACLIN');
INSERT INTO department (id,province_id,name) VALUES(151,2,'SANTA MARIA');
INSERT INTO department (id,province_id,name) VALUES(152,2,'TINOGASTA');
INSERT INTO department (id,province_id,name) VALUES(153,2,'LA PAZ');
INSERT INTO department (id,province_id,name) VALUES(154,2,'VALLE VIEJO');
INSERT INTO department (id,province_id,name) VALUES(155,2,'ANTOFAGASTA DE LA SIERRA');
INSERT INTO department (id,province_id,name) VALUES(156,2,'BELEN');
INSERT INTO department (id,province_id,name) VALUES(157,2,'CAPITAL');
INSERT INTO department (id,province_id,name) VALUES(158,2,'FRAY MAMERTO ESQUIU');
INSERT INTO department (id,province_id,name) VALUES(159,2,'POMAN');
INSERT INTO department (id,province_id,name) VALUES(160,2,'AMBATO');
INSERT INTO department (id,province_id,name) VALUES(161,3,'INDEPENDENCIA');
INSERT INTO department (id,province_id,name) VALUES(162,3,'SAN FERNANDO');
INSERT INTO department (id,province_id,name) VALUES(163,3,'PRIMERO DE MAYO');
INSERT INTO department (id,province_id,name) VALUES(164,3,'FRAY JUSTO SANTA MARIA DE ORO');
INSERT INTO department (id,province_id,name) VALUES(165,3,'SARGENTO CABRAL');
INSERT INTO department (id,province_id,name) VALUES(166,3,'GENERAL GUEMES');
INSERT INTO department (id,province_id,name) VALUES(167,3,'TAPENAGA');
INSERT INTO department (id,province_id,name) VALUES(168,3,'CHACABUCO');
INSERT INTO department (id,province_id,name) VALUES(169,3,'LIBERTADOR GRL.SAN MARTIN');
INSERT INTO department (id,province_id,name) VALUES(170,3,'25 DE MAYO');
INSERT INTO department (id,province_id,name) VALUES(171,3,'12 DE OCTUBRE');
INSERT INTO department (id,province_id,name) VALUES(172,3,'COMANDANTE FERNANDEZ');
INSERT INTO department (id,province_id,name) VALUES(173,3,'QUITILIPI');
INSERT INTO department (id,province_id,name) VALUES(174,3,'MAYOR LUIS J.FONTANA');
INSERT INTO department (id,province_id,name) VALUES(175,3,'LIBERTAD');
INSERT INTO department (id,province_id,name) VALUES(176,3,'BERMEJO');
INSERT INTO department (id,province_id,name) VALUES(177,3,'ALMIRANTE BROWN');
INSERT INTO department (id,province_id,name) VALUES(178,3,'MEYOR LUIS J.FONTANA');
INSERT INTO department (id,province_id,name) VALUES(179,3,'GENERAL BELGRANO');
INSERT INTO department (id,province_id,name) VALUES(180,3,'LIBERTADOR GRL. SAN MARTIN');
INSERT INTO department (id,province_id,name) VALUES(181,3,'GENERAL DONOVAN');
INSERT INTO department (id,province_id,name) VALUES(182,3,'SAN LORENZO');
INSERT INTO department (id,province_id,name) VALUES(183,3,'LEBERTADOR GRL.SAN MARTIN');
INSERT INTO department (id,province_id,name) VALUES(184,3,'MAIPU');
INSERT INTO department (id,province_id,name) VALUES(185,3,'O\'HIGGINS');
INSERT INTO department (id,province_id,name) VALUES(186,3,'9 DE JULIO');
INSERT INTO department (id,province_id,name) VALUES(187,3,'LIBERTADOR SAN MARTIN');
INSERT INTO department (id,province_id,name) VALUES(188,4,'RIO SENGUERR');
INSERT INTO department (id,province_id,name) VALUES(189,4,'MARTIRES');
INSERT INTO department (id,province_id,name) VALUES(190,4,'ESCALANTE');
INSERT INTO department (id,province_id,name) VALUES(191,4,'GAIMAN');
INSERT INTO department (id,province_id,name) VALUES(192,4,'SARMIENTO');
INSERT INTO department (id,province_id,name) VALUES(193,4,'CUSHAMEN');
INSERT INTO department (id,province_id,name) VALUES(194,4,'FLORENTINO AMEGHINO');
INSERT INTO department (id,province_id,name) VALUES(195,4,'PASO DE INDIOS');
INSERT INTO department (id,province_id,name) VALUES(196,4,'TELSEN');
INSERT INTO department (id,province_id,name) VALUES(197,4,'LANGUIÑEO');
INSERT INTO department (id,province_id,name) VALUES(198,4,'GASTRE');
INSERT INTO department (id,province_id,name) VALUES(199,4,'FUTALEUFU');
INSERT INTO department (id,province_id,name) VALUES(200,4,'TEHUELCHES');
INSERT INTO department (id,province_id,name) VALUES(201,4,'RAWSON');
INSERT INTO department (id,province_id,name) VALUES(202,4,'BIEDMA');
INSERT INTO department (id,province_id,name) VALUES(203,5,'RIO CUARTO');
INSERT INTO department (id,province_id,name) VALUES(204,5,'TOTORAL');
INSERT INTO department (id,province_id,name) VALUES(205,5,'COLON');
INSERT INTO department (id,province_id,name) VALUES(206,5,'MINAS');
INSERT INTO department (id,province_id,name) VALUES(207,5,'PUNILLA');
INSERT INTO department (id,province_id,name) VALUES(208,5,'JUAREZ CELMAN');
INSERT INTO department (id,province_id,name) VALUES(209,5,'MARCOS JUAREZ');
INSERT INTO department (id,province_id,name) VALUES(210,5,'SAN JUSTO');
INSERT INTO department (id,province_id,name) VALUES(211,5,'TERCERO ARRIBA');
INSERT INTO department (id,province_id,name) VALUES(212,5,'RIO SECO');
INSERT INTO department (id,province_id,name) VALUES(213,5,'CAPITAL');
INSERT INTO department (id,province_id,name) VALUES(214,5,'SANTA MARIA');
INSERT INTO department (id,province_id,name) VALUES(215,5,'SAN ALBERTO');
INSERT INTO department (id,province_id,name) VALUES(216,5,'UNION');
INSERT INTO department (id,province_id,name) VALUES(217,5,'POCHO');
INSERT INTO department (id,province_id,name) VALUES(218,5,'CALAMUCHITA');
INSERT INTO department (id,province_id,name) VALUES(219,5,'ISCHILIN');
INSERT INTO department (id,province_id,name) VALUES(220,5,'GENERAL SAN MARTIN');
INSERT INTO department (id,province_id,name) VALUES(221,5,'RIO PRIMERO');
INSERT INTO department (id,province_id,name) VALUES(222,5,'CRUZ DEL EJE');
INSERT INTO department (id,province_id,name) VALUES(223,5,'GRL.ROCA');
INSERT INTO department (id,province_id,name) VALUES(224,5,'GENERAL ROCA');
INSERT INTO department (id,province_id,name) VALUES(225,5,'SOBREMONTE');
INSERT INTO department (id,province_id,name) VALUES(226,5,'RIO SEGUNDO');
INSERT INTO department (id,province_id,name) VALUES(227,5,'TULUMBA');
INSERT INTO department (id,province_id,name) VALUES(228,5,'SAN JAVIER');
INSERT INTO department (id,province_id,name) VALUES(229,5,'PRESIDENTE ROQUE SAEZ PEÑA');
INSERT INTO department (id,province_id,name) VALUES(230,5,'PRESIDENTE ROQUE SAENZ PEÑA');
INSERT INTO department (id,province_id,name) VALUES(232,5,'CRUZ DE EJE');
INSERT INTO department (id,province_id,name) VALUES(233,5,'CORONEL PRINGLES');
INSERT INTO department (id,province_id,name) VALUES(234,5,'RIO TERCERO');
INSERT INTO department (id,province_id,name) VALUES(235,5,'CVALAMUCHITA');
INSERT INTO department (id,province_id,name) VALUES(236,6,'SAN ROQUE');
INSERT INTO department (id,province_id,name) VALUES(237,6,'MONTE CASEROS');
INSERT INTO department (id,province_id,name) VALUES(238,6,'GENERAL ALVEAR');
INSERT INTO department (id,province_id,name) VALUES(239,6,'CURUZU CUATIA');
INSERT INTO department (id,province_id,name) VALUES(240,6,'SAN MARTIN');
INSERT INTO department (id,province_id,name) VALUES(241,6,'MERCEDES');
INSERT INTO department (id,province_id,name) VALUES(242,6,'SALADAS');
INSERT INTO department (id,province_id,name) VALUES(243,6,'ITUZAINGO');
INSERT INTO department (id,province_id,name) VALUES(244,6,'BERON DE ASTRADA');
INSERT INTO department (id,province_id,name) VALUES(245,6,'BELLA VISTA');
INSERT INTO department (id,province_id,name) VALUES(246,6,'SAN LUIS DEL PALMAR');
INSERT INTO department (id,province_id,name) VALUES(247,6,'CAPITAL');
INSERT INTO department (id,province_id,name) VALUES(248,6,'LAVALLE');
INSERT INTO department (id,province_id,name) VALUES(249,6,'PASO DE LOS LIBRES');
INSERT INTO department (id,province_id,name) VALUES(250,6,'GOYA');
INSERT INTO department (id,province_id,name) VALUES(251,6,'EMPEDRADO');
INSERT INTO department (id,province_id,name) VALUES(252,6,'SAUCE');
INSERT INTO department (id,province_id,name) VALUES(253,6,'GENERAL PAZ');
INSERT INTO department (id,province_id,name) VALUES(254,6,'SANTO TOME');
INSERT INTO department (id,province_id,name) VALUES(255,6,'SAN MIGUEL');
INSERT INTO department (id,province_id,name) VALUES(256,6,'CONCEPCION');
INSERT INTO department (id,province_id,name) VALUES(257,6,'ESQUINA');
INSERT INTO department (id,province_id,name) VALUES(258,6,'SAN COSME');
INSERT INTO department (id,province_id,name) VALUES(259,6,'ITATI');
INSERT INTO department (id,province_id,name) VALUES(260,6,'MBURUCUYA');
INSERT INTO department (id,province_id,name) VALUES(261,7,'URUGUAY');
INSERT INTO department (id,province_id,name) VALUES(262,7,'NOGOYA');
INSERT INTO department (id,province_id,name) VALUES(263,7,'TALA');
INSERT INTO department (id,province_id,name) VALUES(264,7,'GUALEGUAY');
INSERT INTO department (id,province_id,name) VALUES(265,7,'DIAMANTE');
INSERT INTO department (id,province_id,name) VALUES(266,7,'PARANA');
INSERT INTO department (id,province_id,name) VALUES(267,7,'GUALEGUAYCHU');
INSERT INTO department (id,province_id,name) VALUES(268,7,'COLON');
INSERT INTO department (id,province_id,name) VALUES(269,7,'VICTORIA');
INSERT INTO department (id,province_id,name) VALUES(270,7,'VILLAGUAY');
INSERT INTO department (id,province_id,name) VALUES(271,7,'FELICIANO');
INSERT INTO department (id,province_id,name) VALUES(272,7,'CONCORDIA');
INSERT INTO department (id,province_id,name) VALUES(273,7,'LA PAZ');
INSERT INTO department (id,province_id,name) VALUES(274,7,'FEDERACION');
INSERT INTO department (id,province_id,name) VALUES(275,7,'FEDERAL');
INSERT INTO department (id,province_id,name) VALUES(276,7,'CASTELLANOS');
INSERT INTO department (id,province_id,name) VALUES(277,8,'PILAGAS');
INSERT INTO department (id,province_id,name) VALUES(278,8,'PATIÑO');
INSERT INTO department (id,province_id,name) VALUES(279,8,'PILCOMAYO');
INSERT INTO department (id,province_id,name) VALUES(280,8,'BERMEJO');
INSERT INTO department (id,province_id,name) VALUES(281,8,'PIRANE');
INSERT INTO department (id,province_id,name) VALUES(282,8,'FORMOSA');
INSERT INTO department (id,province_id,name) VALUES(283,8,'MATACOS');
INSERT INTO department (id,province_id,name) VALUES(284,8,'RAMON LISTA');
INSERT INTO department (id,province_id,name) VALUES(285,8,'PILLAGAS');
INSERT INTO department (id,province_id,name) VALUES(286,8,'LAISHI');
INSERT INTO department (id,province_id,name) VALUES(287,9,'LEDESMA');
INSERT INTO department (id,province_id,name) VALUES(288,9,'COCHINOCA');
INSERT INTO department (id,province_id,name) VALUES(289,9,'EL CARMEN');
INSERT INTO department (id,province_id,name) VALUES(290,9,'TUMBAYA');
INSERT INTO department (id,province_id,name) VALUES(291,9,'CAPITAL');
INSERT INTO department (id,province_id,name) VALUES(292,9,'YAVI');
INSERT INTO department (id,province_id,name) VALUES(293,9,'HUMAHUACA');
INSERT INTO department (id,province_id,name) VALUES(294,9,'RINCONADA');
INSERT INTO department (id,province_id,name) VALUES(295,9,'VALLE GRANDE');
INSERT INTO department (id,province_id,name) VALUES(296,9,'SUSQUES');
INSERT INTO department (id,province_id,name) VALUES(297,9,'SANTA CATALINA');
INSERT INTO department (id,province_id,name) VALUES(298,9,'SAN ANTONIO');
INSERT INTO department (id,province_id,name) VALUES(299,9,'SANTA BARBARA');
INSERT INTO department (id,province_id,name) VALUES(300,9,'SAN PEDRO');
INSERT INTO department (id,province_id,name) VALUES(301,9,'TILCARA');
INSERT INTO department (id,province_id,name) VALUES(302,9,'LADESMA');
INSERT INTO department (id,province_id,name) VALUES(303,10,'HUCAL');
INSERT INTO department (id,province_id,name) VALUES(304,10,'REALICO');
INSERT INTO department (id,province_id,name) VALUES(305,10,'MARA CO');
INSERT INTO department (id,province_id,name) VALUES(306,10,'QUEMUQUEMU');
INSERT INTO department (id,province_id,name) VALUES(307,10,'CHICAL CO');
INSERT INTO department (id,province_id,name) VALUES(308,10,'GUATRACHE');
INSERT INTO department (id,province_id,name) VALUES(309,10,'CAPITAL');
INSERT INTO department (id,province_id,name) VALUES(310,10,'CALEUCALEU');
INSERT INTO department (id,province_id,name) VALUES(311,10,'TRENEL');
INSERT INTO department (id,province_id,name) VALUES(312,10,'UTRACAN');
INSERT INTO department (id,province_id,name) VALUES(313,10,'ATREUCO');
INSERT INTO department (id,province_id,name) VALUES(314,10,'TOAY');
INSERT INTO department (id,province_id,name) VALUES(315,10,'CHAPADLEUFU');
INSERT INTO department (id,province_id,name) VALUES(316,10,'CONELO');
INSERT INTO department (id,province_id,name) VALUES(317,10,'PUELEN');
INSERT INTO department (id,province_id,name) VALUES(318,10,'RANCUL');
INSERT INTO department (id,province_id,name) VALUES(319,10,'QUEMU QUEMU');
INSERT INTO department (id,province_id,name) VALUES(320,10,'LOVENTUE');
INSERT INTO department (id,province_id,name) VALUES(321,10,'CONHELO');
INSERT INTO department (id,province_id,name) VALUES(322,10,'CATRILO');
INSERT INTO department (id,province_id,name) VALUES(323,10,'CHAPALEUFU');
INSERT INTO department (id,province_id,name) VALUES(324,10,'ULTRACAN');
INSERT INTO department (id,province_id,name) VALUES(325,10,'CHALILEO');
INSERT INTO department (id,province_id,name) VALUES(326,10,'LIHUEL CALEL');
INSERT INTO department (id,province_id,name) VALUES(327,10,'MARACO');
INSERT INTO department (id,province_id,name) VALUES(328,10,'CALEU CALEU');
INSERT INTO department (id,province_id,name) VALUES(329,10,'CURACO');
INSERT INTO department (id,province_id,name) VALUES(330,10,'LIMAY MAHUIDA');
INSERT INTO department (id,province_id,name) VALUES(331,11,'CASTRO BARROS');
INSERT INTO department (id,province_id,name) VALUES(332,11,'GENERAL SAN MARTIN');
INSERT INTO department (id,province_id,name) VALUES(333,11,'GENERAL LAVALLE');
INSERT INTO department (id,province_id,name) VALUES(334,11,'ARAUCO');
INSERT INTO department (id,province_id,name) VALUES(335,11,'GRAL.ANGEL V.PEÑALOZA');
INSERT INTO department (id,province_id,name) VALUES(336,11,'SAN BLAS DE LOS SAUCES');
INSERT INTO department (id,province_id,name) VALUES(337,11,'INDEPENDENCIA');
INSERT INTO department (id,province_id,name) VALUES(338,11,'GENERAL OCAMPO');
INSERT INTO department (id,province_id,name) VALUES(339,11,'CHILECITO');
INSERT INTO department (id,province_id,name) VALUES(340,11,'FAMATINA');
INSERT INTO department (id,province_id,name) VALUES(341,11,'GRL.JUAN FACUNDO QUIROGA');
INSERT INTO department (id,province_id,name) VALUES(342,11,'GRL.ANGEL V. PEÑALOZA');
INSERT INTO department (id,province_id,name) VALUES(343,11,'GENERAL BELGRANO');
INSERT INTO department (id,province_id,name) VALUES(344,11,'GENERAL SARMIENTO');
INSERT INTO department (id,province_id,name) VALUES(345,11,'CAPITAL');
INSERT INTO department (id,province_id,name) VALUES(346,11,'GDOR. GORDILLO');
INSERT INTO department (id,province_id,name) VALUES(347,11,'GENERAL ANGEL VICENTE PEÑALOZA');
INSERT INTO department (id,province_id,name) VALUES(348,11,'GOBERNADOR GORDILLO');
INSERT INTO department (id,province_id,name) VALUES(349,11,'ROSARIO VERA PEÑALOZA');
INSERT INTO department (id,province_id,name) VALUES(350,11,'GRL.SAN MARTIN');
INSERT INTO department (id,province_id,name) VALUES(351,11,'GENERAL LA MADRID');
INSERT INTO department (id,province_id,name) VALUES(352,11,'GENERAL JUAN FACUNDO QUIROGA');
INSERT INTO department (id,province_id,name) VALUES(353,11,'GENERALOCAMPO');
INSERT INTO department (id,province_id,name) VALUES(354,11,'SANAGASTA');
INSERT INTO department (id,province_id,name) VALUES(355,12,'SAN RAFAEL');
INSERT INTO department (id,province_id,name) VALUES(356,12,'LUJAN');
INSERT INTO department (id,province_id,name) VALUES(357,12,'MALARGUE');
INSERT INTO department (id,province_id,name) VALUES(358,12,'GUAYMALLEN');
INSERT INTO department (id,province_id,name) VALUES(359,12,'LAVALLE');
INSERT INTO department (id,province_id,name) VALUES(360,12,'JUNIN');
INSERT INTO department (id,province_id,name) VALUES(361,12,'TUPUNGATO');
INSERT INTO department (id,province_id,name) VALUES(362,12,'RIVADAVIA');
INSERT INTO department (id,province_id,name) VALUES(363,12,'MAIPU');
INSERT INTO department (id,province_id,name) VALUES(364,12,'GODOY CRUZ');
INSERT INTO department (id,province_id,name) VALUES(365,12,'GENERAL ALVEAR');
INSERT INTO department (id,province_id,name) VALUES(366,12,'LA PAZ');
INSERT INTO department (id,province_id,name) VALUES(367,12,'TUNUYAN');
INSERT INTO department (id,province_id,name) VALUES(368,12,'SAN CARLOS');
INSERT INTO department (id,province_id,name) VALUES(369,12,'LAS HERAS');
INSERT INTO department (id,province_id,name) VALUES(370,12,'LUJAN DE CUYO');
INSERT INTO department (id,province_id,name) VALUES(371,12,'SAN MARTIN');
INSERT INTO department (id,province_id,name) VALUES(372,12,'SANTA ROSA');
INSERT INTO department (id,province_id,name) VALUES(373,12,'CAPITAL');
INSERT INTO department (id,province_id,name) VALUES(374,13,'25 DE MAYO');
INSERT INTO department (id,province_id,name) VALUES(375,13,'IGUAZU');
INSERT INTO department (id,province_id,name) VALUES(376,13,'EL DORADO');
INSERT INTO department (id,province_id,name) VALUES(377,13,'LEANDRO N. ALEM');
INSERT INTO department (id,province_id,name) VALUES(378,13,'APOSTOLES');
INSERT INTO department (id,province_id,name) VALUES(379,13,'CAINGUAS');
INSERT INTO department (id,province_id,name) VALUES(380,13,'LEANDRO N.ALEM');
INSERT INTO department (id,province_id,name) VALUES(381,13,'CONCEPCION');
INSERT INTO department (id,province_id,name) VALUES(382,13,'SAN PEDRO');
INSERT INTO department (id,province_id,name) VALUES(383,13,'CANDELARIA');
INSERT INTO department (id,province_id,name) VALUES(384,13,'GRL.MANUEL BELGRANO');
INSERT INTO department (id,province_id,name) VALUES(385,13,'OBERA');
INSERT INTO department (id,province_id,name) VALUES(386,13,'LIBERTADOR GRL.SAN MARTIN');
INSERT INTO department (id,province_id,name) VALUES(387,13,'SAN IGNACIO');
INSERT INTO department (id,province_id,name) VALUES(388,13,'MONTECARLO');
INSERT INTO department (id,province_id,name) VALUES(389,13,'GENERAL MANUEL BELGRANO');
INSERT INTO department (id,province_id,name) VALUES(390,13,'LEBERTADOR GRL.SAN MARTIN');
INSERT INTO department (id,province_id,name) VALUES(391,13,'EL GUARANI');
INSERT INTO department (id,province_id,name) VALUES(392,13,'ELDORADO');
INSERT INTO department (id,province_id,name) VALUES(393,13,'CAPITAL');
INSERT INTO department (id,province_id,name) VALUES(394,13,'GUARANI');
INSERT INTO department (id,province_id,name) VALUES(395,13,'SAN JAVIER');
INSERT INTO department (id,province_id,name) VALUES(396,13,'LIBERTADOR GRL. SAN MARTIN');
INSERT INTO department (id,province_id,name) VALUES(397,14,'COLLON CURA');
INSERT INTO department (id,province_id,name) VALUES(398,14,'ALUMINE');
INSERT INTO department (id,province_id,name) VALUES(399,14,'MINAS');
INSERT INTO department (id,province_id,name) VALUES(400,14,'AÑELO');
INSERT INTO department (id,province_id,name) VALUES(401,14,'CONFLUENCIA');
INSERT INTO department (id,province_id,name) VALUES(402,14,'CHOS MALAL');
INSERT INTO department (id,province_id,name) VALUES(403,14,'PICUNCHES');
INSERT INTO department (id,province_id,name) VALUES(404,14,'NORQUIN');
INSERT INTO department (id,province_id,name) VALUES(405,14,'PEHUENCHES');
INSERT INTO department (id,province_id,name) VALUES(406,14,'LONCOPUE');
INSERT INTO department (id,province_id,name) VALUES(407,14,'HUILICHES');
INSERT INTO department (id,province_id,name) VALUES(408,14,'ZAPALA');
INSERT INTO department (id,province_id,name) VALUES(409,14,'CATAN LIL');
INSERT INTO department (id,province_id,name) VALUES(410,14,'ÑORQUIN');
INSERT INTO department (id,province_id,name) VALUES(411,14,'LOS LAGOS');
INSERT INTO department (id,province_id,name) VALUES(412,14,'PICUN LEUFU');
INSERT INTO department (id,province_id,name) VALUES(413,14,'LACAR');
INSERT INTO department (id,province_id,name) VALUES(414,14,'ÑOEQUIN');
INSERT INTO department (id,province_id,name) VALUES(415,15,'VALCHETA');
INSERT INTO department (id,province_id,name) VALUES(416,15,'25 DE MAYO');
INSERT INTO department (id,province_id,name) VALUES(417,15,'EL CUY');
INSERT INTO department (id,province_id,name) VALUES(418,15,'ÑORQUINCO');
INSERT INTO department (id,province_id,name) VALUES(419,15,'GENERAL ROCA');
INSERT INTO department (id,province_id,name) VALUES(420,15,'AVELLANEDA');
INSERT INTO department (id,province_id,name) VALUES(421,15,'CONESA');
INSERT INTO department (id,province_id,name) VALUES(422,15,'PICHI MAHUIDA');
INSERT INTO department (id,province_id,name) VALUES(423,15,'SAN ANTONIO');
INSERT INTO department (id,province_id,name) VALUES(424,15,'PILCANIYEU');
INSERT INTO department (id,province_id,name) VALUES(425,15,'9 DE JULIO');
INSERT INTO department (id,province_id,name) VALUES(426,15,'ADOLFO ALSINA');
INSERT INTO department (id,province_id,name) VALUES(427,15,'BARILOCHE');
INSERT INTO department (id,province_id,name) VALUES(428,15,'PIHI MAHUIDA');
INSERT INTO department (id,province_id,name) VALUES(429,16,'LA VIÑA');
INSERT INTO department (id,province_id,name) VALUES(430,16,'SAN MARTIN');
INSERT INTO department (id,province_id,name) VALUES(431,16,'ORAN');
INSERT INTO department (id,province_id,name) VALUES(432,16,'ANTA');
INSERT INTO department (id,province_id,name) VALUES(433,16,'GRAL.JOSE DE SAN MARTIN');
INSERT INTO department (id,province_id,name) VALUES(434,16,'GUACHIPAS');
INSERT INTO department (id,province_id,name) VALUES(435,16,'ROSARIO DE LA FRONTERA');
INSERT INTO department (id,province_id,name) VALUES(436,16,'RIVADAVIA');
INSERT INTO department (id,province_id,name) VALUES(437,16,'METAN');
INSERT INTO department (id,province_id,name) VALUES(438,16,'SAN CARLOS');
INSERT INTO department (id,province_id,name) VALUES(439,16,'GRL.GUEMES');
INSERT INTO department (id,province_id,name) VALUES(440,16,'CACHI');
INSERT INTO department (id,province_id,name) VALUES(441,16,'ROSARIO DE LERMA');
INSERT INTO department (id,province_id,name) VALUES(442,16,'CAFAYATE');
INSERT INTO department (id,province_id,name) VALUES(443,16,'LOS ANDES');
INSERT INTO department (id,province_id,name) VALUES(444,16,'GRL.JOSE DE SAN MARTIN');
INSERT INTO department (id,province_id,name) VALUES(445,16,'CAPITAL');
INSERT INTO department (id,province_id,name) VALUES(446,16,'GRL.SAN MARTIN');
INSERT INTO department (id,province_id,name) VALUES(447,16,'GENERAL GUEMES');
INSERT INTO department (id,province_id,name) VALUES(448,16,'CERRILLOS');
INSERT INTO department (id,province_id,name) VALUES(449,16,'CHICOANA');
INSERT INTO department (id,province_id,name) VALUES(450,16,'LA POMA');
INSERT INTO department (id,province_id,name) VALUES(451,16,'LA CAPITAL');
INSERT INTO department (id,province_id,name) VALUES(452,16,'CANDELARIA');
INSERT INTO department (id,province_id,name) VALUES(453,16,'ROSARIO');
INSERT INTO department (id,province_id,name) VALUES(454,16,'IRUYA');
INSERT INTO department (id,province_id,name) VALUES(455,16,'LA CALDERA');
INSERT INTO department (id,province_id,name) VALUES(456,16,'LOA ANDES');
INSERT INTO department (id,province_id,name) VALUES(457,16,'MOLINOS');
INSERT INTO department (id,province_id,name) VALUES(458,16,'SANTA VICTORIA');
INSERT INTO department (id,province_id,name) VALUES(459,17,'9 DE JULIO');
INSERT INTO department (id,province_id,name) VALUES(460,17,'JACHAL');
INSERT INTO department (id,province_id,name) VALUES(461,17,'ALBARDON');
INSERT INTO department (id,province_id,name) VALUES(462,17,'25 DE MAYO');
INSERT INTO department (id,province_id,name) VALUES(463,17,'SANTA LUCIA');
INSERT INTO department (id,province_id,name) VALUES(464,17,'ANGACO');
INSERT INTO department (id,province_id,name) VALUES(465,17,'IGLESIA');
INSERT INTO department (id,province_id,name) VALUES(466,17,'VALLE FERTIL');
INSERT INTO department (id,province_id,name) VALUES(467,17,'CALINGASTA');
INSERT INTO department (id,province_id,name) VALUES(468,17,'RIVADAVIA');
INSERT INTO department (id,province_id,name) VALUES(469,17,'CAUCETE');
INSERT INTO department (id,province_id,name) VALUES(470,17,'SARMIENTO');
INSERT INTO department (id,province_id,name) VALUES(471,17,'POCITO');
INSERT INTO department (id,province_id,name) VALUES(472,17,'SAN MARTIN');
INSERT INTO department (id,province_id,name) VALUES(473,17,'CHIMBAS');
INSERT INTO department (id,province_id,name) VALUES(474,17,'IGLESIAS');
INSERT INTO department (id,province_id,name) VALUES(475,17,'ULLUN');
INSERT INTO department (id,province_id,name) VALUES(476,17,'RAWSON');
INSERT INTO department (id,province_id,name) VALUES(477,17,'CAPITAL');
INSERT INTO department (id,province_id,name) VALUES(478,17,'ZONDA');
INSERT INTO department (id,province_id,name) VALUES(479,18,'BELGRANO');
INSERT INTO department (id,province_id,name) VALUES(480,18,'CHACABUCO');
INSERT INTO department (id,province_id,name) VALUES(481,18,'LA CAPITAL');
INSERT INTO department (id,province_id,name) VALUES(482,18,'GOBERNADOR DUPUY');
INSERT INTO department (id,province_id,name) VALUES(483,18,'GRL.PEDERNERA');
INSERT INTO department (id,province_id,name) VALUES(484,18,'AYACUCHO');
INSERT INTO department (id,province_id,name) VALUES(485,18,'JUNIN');
INSERT INTO department (id,province_id,name) VALUES(486,18,'GONERNADOR DUPUY');
INSERT INTO department (id,province_id,name) VALUES(487,18,'CORONEL PRINGLES');
INSERT INTO department (id,province_id,name) VALUES(488,18,'GENERAL PEDERNERA');
INSERT INTO department (id,province_id,name) VALUES(489,18,'GOBERNADOR DUVAL');
INSERT INTO department (id,province_id,name) VALUES(490,18,'IGLESIA');
INSERT INTO department (id,province_id,name) VALUES(491,18,'LIBERTADOR GRL. SAN MARTIN');
INSERT INTO department (id,province_id,name) VALUES(492,18,'LIBERTADOR GRL.SAN MARTIN');
INSERT INTO department (id,province_id,name) VALUES(493,18,'LIBERTADOR GR.SAN MARTIN');
INSERT INTO department (id,province_id,name) VALUES(494,18,'CAUCETE');
INSERT INTO department (id,province_id,name) VALUES(495,19,'GUER AIKE');
INSERT INTO department (id,province_id,name) VALUES(496,19,'DESEADO');
INSERT INTO department (id,province_id,name) VALUES(497,19,'RIO CHICO');
INSERT INTO department (id,province_id,name) VALUES(498,19,'MAGALLANES');
INSERT INTO department (id,province_id,name) VALUES(499,19,'LAGO ARGENTINO');
INSERT INTO department (id,province_id,name) VALUES(500,19,'CORPEN AIKE');
INSERT INTO department (id,province_id,name) VALUES(501,19,'LAGO BUENOS AIRES');
INSERT INTO department (id,province_id,name) VALUES(502,20,'GENERAL LOPEZ');
INSERT INTO department (id,province_id,name) VALUES(503,20,'ROSARIO');
INSERT INTO department (id,province_id,name) VALUES(504,20,'GENERAL OBLIGADO');
INSERT INTO department (id,province_id,name) VALUES(505,20,'CONSTITUCION');
INSERT INTO department (id,province_id,name) VALUES(506,20,'SAN LORENZO');
INSERT INTO department (id,province_id,name) VALUES(507,20,'SAN JAVIER');
INSERT INTO department (id,province_id,name) VALUES(508,20,'LA CAPITAL');
INSERT INTO department (id,province_id,name) VALUES(509,20,'SAN CRISTOBAL');
INSERT INTO department (id,province_id,name) VALUES(510,20,'IRIONDO');
INSERT INTO department (id,province_id,name) VALUES(511,20,'CASTELLANOS');
INSERT INTO department (id,province_id,name) VALUES(512,20,'NUEVE DE JULIO');
INSERT INTO department (id,province_id,name) VALUES(513,20,'CASEROS');
INSERT INTO department (id,province_id,name) VALUES(514,20,'SAN JERONIMO');
INSERT INTO department (id,province_id,name) VALUES(515,20,'BELGRANO');
INSERT INTO department (id,province_id,name) VALUES(516,20,'CAPITAL');
INSERT INTO department (id,province_id,name) VALUES(517,20,'SAN JUSTO');
INSERT INTO department (id,province_id,name) VALUES(518,20,'GRL.OBLIGADO');
INSERT INTO department (id,province_id,name) VALUES(519,20,'LA CAPUTAL');
INSERT INTO department (id,province_id,name) VALUES(520,20,'GRL.LOPEZ');
INSERT INTO department (id,province_id,name) VALUES(521,20,'VERA');
INSERT INTO department (id,province_id,name) VALUES(522,20,'9 DE JULIO');
INSERT INTO department (id,province_id,name) VALUES(523,20,'SAN MARTIN');
INSERT INTO department (id,province_id,name) VALUES(524,20,'LAS COLONIAS');
INSERT INTO department (id,province_id,name) VALUES(525,20,'GARAY');
INSERT INTO department (id,province_id,name) VALUES(526,20,'CASTELANOS');
INSERT INTO department (id,province_id,name) VALUES(527,20,'LAS COLINAS');
INSERT INTO department (id,province_id,name) VALUES(528,21,'BANDA');
INSERT INTO department (id,province_id,name) VALUES(529,21,'MORENO');
INSERT INTO department (id,province_id,name) VALUES(530,21,'ALBERDI');
INSERT INTO department (id,province_id,name) VALUES(531,21,'PELLEGRINI');
INSERT INTO department (id,province_id,name) VALUES(532,21,'OJO DE AGUA');
INSERT INTO department (id,province_id,name) VALUES(533,21,'RIO HONDO');
INSERT INTO department (id,province_id,name) VALUES(534,21,'GENERAL TABOADA');
INSERT INTO department (id,province_id,name) VALUES(535,21,'CHOYA');
INSERT INTO department (id,province_id,name) VALUES(536,21,'CAPITAL');
INSERT INTO department (id,province_id,name) VALUES(537,21,'AGUIRRE');
INSERT INTO department (id,province_id,name) VALUES(538,21,'SILIPICA');
INSERT INTO department (id,province_id,name) VALUES(539,21,'BELGRANO');
INSERT INTO department (id,province_id,name) VALUES(540,21,'FIGUEROA');
INSERT INTO department (id,province_id,name) VALUES(541,21,'SALAVINA');
INSERT INTO department (id,province_id,name) VALUES(542,21,'QUEBRACHOS');
INSERT INTO department (id,province_id,name) VALUES(543,21,'ROBLES');
INSERT INTO department (id,province_id,name) VALUES(544,21,'AVELLANEDA');
INSERT INTO department (id,province_id,name) VALUES(545,21,'JIMENEZ');
INSERT INTO department (id,province_id,name) VALUES(546,21,'ATAMISQUI');
INSERT INTO department (id,province_id,name) VALUES(547,21,'SAN MARTIN');
INSERT INTO department (id,province_id,name) VALUES(548,21,'MATARA');
INSERT INTO department (id,province_id,name) VALUES(549,21,'SALAYINA');
INSERT INTO department (id,province_id,name) VALUES(550,21,'GUASAYAN');
INSERT INTO department (id,province_id,name) VALUES(551,21,'COPO');
INSERT INTO department (id,province_id,name) VALUES(552,21,'BRIGADIER JUAN FELIPE IBARRA');
INSERT INTO department (id,province_id,name) VALUES(553,21,'DOBLES');
INSERT INTO department (id,province_id,name) VALUES(554,21,'SARMIENTO');
INSERT INTO department (id,province_id,name) VALUES(555,21,'LORETO');
INSERT INTO department (id,province_id,name) VALUES(556,21,'MITRE');
INSERT INTO department (id,province_id,name) VALUES(557,21,'RIVADAVIA');
INSERT INTO department (id,province_id,name) VALUES(558,22,'USHUAIA');
INSERT INTO department (id,province_id,name) VALUES(559,22,'ISLAS DEL ATLANTICO SUR');
INSERT INTO department (id,province_id,name) VALUES(560,22,'SECTOR ANTARTICO ARGENTINO');
INSERT INTO department (id,province_id,name) VALUES(561,22,'RIO GRANDE');
INSERT INTO department (id,province_id,name) VALUES(562,22,'IS.DEL ATLANTICO SUR E IS.MALVINAS');
INSERT INTO department (id,province_id,name) VALUES(563,22,'ANTARTIDA ARGENTINA');
INSERT INTO department (id,province_id,name) VALUES(564,23,'BURRUYACU');
INSERT INTO department (id,province_id,name) VALUES(565,23,'TRANCAS');
INSERT INTO department (id,province_id,name) VALUES(566,23,'MONTEROS');
INSERT INTO department (id,province_id,name) VALUES(567,23,'LEALES');
INSERT INTO department (id,province_id,name) VALUES(568,23,'CRUZ ALTA');
INSERT INTO department (id,province_id,name) VALUES(569,23,'RIO CHICO');
INSERT INTO department (id,province_id,name) VALUES(570,23,'CHICLIGASTA');
INSERT INTO department (id,province_id,name) VALUES(571,23,'TAFI');
INSERT INTO department (id,province_id,name) VALUES(572,23,'GRANEROS');
INSERT INTO department (id,province_id,name) VALUES(573,23,'FAMAILLA');
INSERT INTO department (id,province_id,name) VALUES(574,23,'CAPITAL');
INSERT INTO department (id,province_id,name) VALUES(575,24,'CAPITAL FEDERAL');