<?php

namespace UnaGauchada\PublicationBundle\Repository;

/**
 * AcceptedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcceptedRepository extends \Doctrine\ORM\EntityRepository
{
}
