<?php

namespace UnaGauchada\PublicationBundle\Repository;
use UnaGauchada\UserBundle\Entity\User;

/**
 * AchievementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AchievementRepository extends \Doctrine\ORM\EntityRepository
{

    public function findFor(User $user){
        $qb = $this->createQueryBuilder('a')
            ->where('a.min <= :calification')
            ->andWhere('a.max >= :calification')
            ->setParameter('calification', $user->getCalification())
            ->getQuery();

        return $qb->getSingleResult();
    }

}
