<?php

namespace UnaGauchada\PublicationBundle\Repository;
use UnaGauchada\UserBundle\Entity\User;

/**
 * AchievementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AchievementRepository extends \Doctrine\ORM\EntityRepository
{

    public function findFor(User $user){
        $qb = $this->createQueryBuilder('a')
            ->where('a.min <= :score')
            ->andWhere('a.max >= :score')
            ->setParameter('score', $user->getScore())
            ->getQuery();

        return $qb->getSingleResult();
    }

}
