<?php

namespace UnaGauchada\PublicationBundle\Repository;

/**
 * PublicationCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
