<?php

namespace UnaGauchada\PublicationBundle\Repository;

/**
 * QualificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QualificationRepository extends \Doctrine\ORM\EntityRepository
{
}
